AWSTemplateFormatVersion: 2010-09-09
Description: CI/CD pipeline for github projects

Resources:
  rGlueDatabase:
    Type: 'AWS::Glue::Database'
    Properties:
      Catalogid: !Ref AWS::AccountId
      DatabaseInput:
        Name: 'hello'
        Description: Sample glue database
